######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 24 07:31:18 2008
######################################################################

DYNAMOL_HOME = /home/jfurr/New_Build/

TEMPLATE = lib
TARGET = 	iterator_ext.so

CONFIG += dll release
DEFINES += BOOST_PYTHON_DYNAMIC_LIB
DEPENDPATH += .

INCLUDEPATH += . $$DYNAMOL_HOME/usr/local/include/python2.5 \
                $$DYNAMOL_HOME/usr/local/include/python2.5/config \
                $$DYNAMOL_HOME/boost_1_34_1/boost/python \
                $$DYNAMOL_HOME/boost_1_34_1/boost \
                $$DYNAMOL_HOME/boost_1_34_1

LIBS += -lutil -lpthread -ldl \
        $$DYNAMOL_HOME/usr/local/lib/python2.5/config/libpython2.5.a \
        $$DYNAMOL_HOME/usr/local/lib/libboost_python-gcc41-d-1_34_1.so.1.34.1 
		#$$DYNAMOL_HOME/Dynamol/dynamol/*.o 


# Input
SOURCES += 	*.cpp
