######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 17 13:51:33 2007
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += atom.h atomflyweightfactory.h atomintstate.h utility.h
SOURCES += atom.cpp \
           atomflyweightfactory.cpp \
           atomintstate.cpp \
           dynabase.cpp \
           utility.cpp
