#!/bin/sh

uic gaff_fp_progress.ui -o gaff_fp_progress.h
uic -impl gaff_fp_progress.h gaff_fp_progress.ui > gaff_fp_progress.cpp

cp gaff_fp_progress.h ../../src
cp gaff_fp_progress.cpp ../../src
cp gaff_fp_progress.ui.h ../../src

