######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 24 07:31:18 2008
######################################################################

TEMPLATE = lib
TARGET = 	molecule

CONFIG += plugin
DEFINES += BOOST_PYTHON_DYNAMIC_LIB
DEPENDPATH += .


###########################################
####### OS X BUILD SECTION ################
###########################################
macx {
    message("OSX BUild")    
    QMAKE_CXXFLAGS += -std=c++11 -stdlib=libc++
    QMAKE_LFLAGS += -lc++
    DESTDIR= ../../Scripts

	DYNAMOL_HOME = /Users/jfurr/dynamol
	INCLUDEPATH += . /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 \ 
		/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config \
        /usr/local/include/ \


    LIBS += -L/usr/local/lib \
        -lpython2.7 \
        #-pthread\
        /Users/jfurr/Downloads/boost_1_57_0/bin.v2/libs/python/build/darwin-4.2.1/release/threading-multi/libboost_python.dylib \
	    $$DYNAMOL_HOME/dynamol/molecule.o \	
	    $$DYNAMOL_HOME/dynamol/atom.o	\
	    $$DYNAMOL_HOME/dynamol/bond.o \
	    $$DYNAMOL_HOME/dynamol/dyobject.o	

    # Python wants the library name to be molecule.so when we import molecule.
    QMAKE_PRE_LINK = rm -f molecule.so
    QMAKE_POST_LINK = ln -s libmolecule.dylib molecule.so; ln -s libmolecule.dylib ../../Scripts/molecule.so
    QMAKE_CLEAN = molecule.so ../../Scripts/molecule.so ../../Scripts/libmolecule.dylib    


}

SOURCES += *.cpp
