######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 20 06:45:38 2007
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS = -L../dynatype -ldynatype -L../dynabase -ldynabase
# Input
HEADERS += convert.h 
SOURCES += convert.cpp 
