######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 22 07:45:29 2008
######################################################################

DYNAMOL_HOME = /home/jfurr/New_Build

TEMPLATE = app
TARGET = Dynamol
DEPENDPATH += .
DEFINES += BOOST_PYTHON_STATIC_LIB PyMol

QT += opengl

###########################################
####### OS X BUILD SECTION ################
###########################################
macx {

        DYNAMOL_HOME = /Users/jfurr/Dynamol/

        INCLUDEPATH += . /Library/Frameworks/Python.framework/Versions/2.5/include/python2.5 \
                /Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/config \
                /Users/jfurr/Boost/boost/python \
                /Users/jfurr/Boost/boost \
                /Users/jfurr/Boost


        LIBS += -lutil -lpthread -ldl \
        /Library/Frameworks/Python.framework/Versions/2.5/Python \
        -L/Library/Frameworks/Python.framework/Versions/2.5/lib \
        -L/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/config \
        /Users/jfurr/Boost/bin.v2/libs/python/build/darwin/debug/libboost_python-d-1_34_1.dylib 
        #$$DYNAMOL_HOME/Dynamol/dynamol/molecule.o \
        #$$DYNAMOL_HOME/Dynamol/dynamol/atom.o   \
        #$$DYNAMOL_HOME/Dynamol/dynamol/bond.o

}

############################################
######## LINUX BUILD SECTION ###############
############################################
linux-g++ {

	INCLUDEPATH += . $$DYNAMOL_HOME/usr/local/include/python2.5 \
		$$DYNAMOL_HOME/usr/local/include/python2.5/config \
		$$DYNAMOL_HOME/boost_1_34_1/boost/python \
		$$DYNAMOL_HOME/boost_1_34_1/boost \
		$$DYNAMOL_HOME/boost_1_34_1


	#DEFINES += BOOST_PYTHON_STATIC_LIB Dynamol

	LIBS += -lutil -lpthread -ldl \
		$$DYNAMOL_HOME/usr/local/lib/python2.5/config/libpython2.5.a \
		$$DYNAMOL_HOME/usr/local/lib/libboost_python-gcc41-d-1_34_1.so.1.34.1
}

QT += opengl

# Input
#HEADERS += *.h
#SOURCES += *.cpp

HEADERS +=	enumTypes.h \
			linAlg.h \
			mousesensor.h \
			quat.h \
			trackball.h \
			molview_control.h \
			molview.h \
			atom.h \
			bond.h \
			enumTypes.h \
			molecule.h \
			dynapy.h \
			script_molview.h \
			molview_layout.h \
			scriptengine.h \
			dyobject.h


SOURCES +=	linAlg.cpp \
			main.cpp \
			mousesensor.cpp \
			quat.cpp \
			trackball.cpp \
			molview_control.cpp \
			molview.cpp \
			atom.cpp \
			bond.cpp \
			molecule.cpp \
			dynapy.cpp \
			script_molview.cpp \
			scriptengine.cpp \
			dyobject.cpp
			
FORMS += 	MainWindow.ui 
