# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/installer

HEADERS += installer.h \
           envprompt.h 
SOURCES += installer.cpp \
           main.cpp \
           envprompt.cpp 
TEMPLATE = app
CONFIG += release \
warn_on \
thread \
qt
TARGET = ../bin/installer
